%% initialize environments
clc;
clear variables;

%% make long term average spectrum mat file
band_list = [
    "めどれみ", ...
    "シャンディタウン", ...
    "ビート・ビート・ビート", ...
    "太陽の破片", ...
    "すばる", ...
    "ささめき", ...
    "ジュリアナイト", ...
    "しっくすなっつ", ...
    "チョコミン党", ...
    "ラボラトリア", ...
    "ジュークボックス", ...
    "バリバリ" ...
];

for band_list_index = 1 : length(band_list)
    %% load Tandem Straight spectorgram noMask mat file
    mat_file_path ="D:/アカペラ/はもねぷ 2022 冬 音源/mat_files/world_spectrogram/" + band_list(band_list_index) + ".mat";
    spectrogram = load(mat_file_path);
    spectrogram = spectrogram.spectrogram;
    disp(mat_file_path)
    column_size = size(spectrogram.spectrum_parameters.spectrogram, 2);
    spectrogram.long_term_average_spectrum = sum(spectrogram.spectrum_parameters.spectrogram, 2) ./ column_size;
    spectrogram_path = "D:/アカペラ/はもねぷ 2022 冬 音源/mat_files/long_term_average_spectrum/" + band_list(band_list_index) + ".mat";
    save(spectrogram_path, "spectrogram");
end