% ファイルを操作する際のパラメータ
inputFilePath = "D:/名城大学/研究室/演習/data/F009_ATR503_A01_T01_8k.raw";
outputFilePath = "D:/名城大学/研究室/演習/data/F009_ATR503_A01_T01_8kCepstrum.raw";
samplingFrequency = 8000;
dataType = "int16";

% ファイル操作用のオブジェクトを生成
fileManipulator = FileManipulator( ...
    inputFilePath, ...
    outputFilePath, ...
    samplingFrequency, ...
    dataType ...
);