%% ファイルを操作する際のパラメータ
inputFilePath = "D:\名城大学\研究室\演習\data\M007_ATR503_A01_T01.raw";
outputFilePath = "D:\名城大学\研究室\演習\data\outputTest.raw";
samplingFrequency = 8000;
dataType = "int16";

%% ファイル操作用のオブジェクトを生成
fileManipulator = FileManipulator( ...
    inputFilePath, ...
    outputFilePath, ...
    samplingFrequency, ...
    dataType ...
);

% fileManipulator.clearEnviornments();

%% 分析をする際のパラメータ
startPoint = 8308;  % スタート位置
FFTPoint = 2 ^ 9;  % FFTを行う際の次元数
maxCepstrumDimension =21;  % 高ケフレンシー成分
threshold = 0.1;   % 有声音か無声音かを判定する際の閾値
repeatNumber = 100; % 基本周期で繰り返す回数
basicPeriodGain = 1;    % 基本周期の間隔のゲイン

%% 分析する為のオブジェクトを生成
cepstrum = Cepstrum( ...
    fileManipulator.originalSignal(startPoint : startPoint + 240 - 1), ...
    fileManipulator.samplingFrequency, ...
    FFTPoint, ...
    maxCepstrumDimension, ...
    threshold, ...
    repeatNumber, ...
    basicPeriodGain ...
);

%% Plotterオブジェクトを生成する際のパラメータ
xLabel = "周波数 [Hz]";
yLabel = "振幅 [dB]";
titleLabel = "ケプストラム分析による振幅スペクトルとスペクトル包絡";
maxValue = 2 ^ 15;
outputImageFilePath = "D:\名城大学\研究室\演習\data\compareEnvelopeAndAmplitude";

%% Plotterオブジェクトを生成する
plotter = Plotter( ...
    20 * log10(cepstrum.linearAmplitudedSpectralEnvelope / maxValue), ...
    20 * log10(cepstrum.linearAmplitudeSpectral / maxValue), ...
    samplingFrequency, ...
    FFTPoint, ...
    xLabel, ...
    yLabel, ...
    titleLabel, ...
    outputImageFilePath ...
);