% ファイルを操作する際のパラメータ
inputFilePath = "D:\名城大学\研究室\演習\data\M007_ATR503_A01_T01.raw";
outputFilePath = "D:\名城大学\研究室\演習\data\outputTest.raw";
samplingFrequency = 8000;
dataType = "int16";

% ファイル操作用のオブジェクトを生成
fileManipulator = FileManipulator( ...
    inputFilePath, ...
    outputFilePath, ...
    samplingFrequency, ...
    dataType ...
);

fileManipulator.displayProperties();