%% initialize environments
clc;
clear variables;

%% plot all 4 mora word list audio files
band_list = [
    "めどれみ", ...
    "シャンディタウン", ...
    "ビート・ビート・ビート", ...
    "太陽の破片", ...
    "すばる", ...
    "ささめき", ...
    "ジュリアナイト", ...
    "しっくすなっつ", ...
    "チョコミン党", ...
    "ラボラトリア", ...
    "ジュークボックス", ...
    "バリバリ" ...
];

for band_list_index = 1 : length(band_list)
    %% load spectrogram mat file and calculate dynamic feature
    mat_file_path ="D:/アカペラ/はもねぷ 2022 冬 音源/mat_files/world_spectrogram/" + band_list(band_list_index) + ".mat";
    spectrogram = load(mat_file_path);
    spectrogram = spectrogram.spectrogram;
    disp(mat_file_path);
    delta_cepstrum_prameters.msdceptime = 50;
    liftering_order = delta_cepstrum_prameters.msdceptime - 5;
    cepstrum = getSt2Cep(spectrogram.spectrum_parameters.spectrogram, liftering_order);
    delta_cepstrum = getDeltaCep4(cepstrum, delta_cepstrum_prameters);
    delta_cepstrum = trunc2(delta_cepstrum, round(delta_cepstrum_prameters.msdceptime / 2), 2, 'both', 1, 0);
    dynamic_feature = getDcepNorm_ver2(delta_cepstrum, 1);
    dynamic_feature_mat_file_path = "D:/アカペラ/はもねぷ 2022 冬 音源/mat_files/dynamic_feature/" + band_list(band_list_index) + ".mat";
    save(dynamic_feature_mat_file_path, "spectrogram", "delta_cepstrum_prameters", "liftering_order", "cepstrum", "delta_cepstrum", "dynamic_feature");
end