function [Hd b] = Bandtest(Fs, N, Fc1, Fc2)
%BANDTEST 離散時間フィルター オブジェクトを返します。

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 16-May-2016 17:32:21

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
% Fs = 16000;  % Sampling Frequency
% 
% N    = 20;       % Order
% Fc1  = 1;        % First Cutoff Frequency
% Fc2  = 5000;     % Second Cutoff Frequency
% flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter
% Create the window vector for the design algorithm.
% win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass');
Hd = dfilt.dffir(b);

% [EOF]
