%% clear cache
clc;
clear variables;

%% open audio file
inputFilePath = "vaiueo2d.wav";
audioFileManipulator = AudioFileManipulator( ...
    inputFilePath ...
);

%% set parameters
start_point = 3748;  % あのスタート位置
continue_time = 30; % [ms]
continue_point = int32(continue_time * audioFileManipulator.information.SampleRate / 1000);
window_mode = "hamming";
dimension = 20;
fft_point = 2 ^ 10;
threshold = 0.001;
frame_length = 32;
hop_length = 8;

%% generate LPCVocoder instance
lpc_vocoder = LPCVocoder( ...
    audioFileManipulator.signal, ...
    window_mode, ...
    fft_point, ...
    dimension, ...
    threshold, ...
    audioFileManipulator.information.SampleRate, ...
    frame_length, ...
    hop_length ...
);
lpc_vocoder.display_properties();