function mapmanipulate2()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load mapmanipulate2                    

a = figure('BackingStore','off', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Position',[337 324 626 393], ...
	'Tag','bendlinemanipulator', ...
	'WindowButtonDownFcn','bendline down', ...
	'WindowButtonUpFcn','bendline up');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[490 2 134 389], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.733333 0.733333 0.733333], ...
	'Position',[500 253 98 20], ...
	'String','original frequency', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.733333 0.733333 0.733333], ...
	'Position',[500 215 98 20], ...
	'String','new frequency', ...
	'Style','text', ...
	'Tag','StaticText2');
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Position',[0.127796 0.111959 0.576677 0.814249], ...
	'Tag','mapaxis', ...
	'XColor',[0 0 0], ...
	'XGrid','on', ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YGrid','on', ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0], ...
	'ZGrid','on');
c = line('Parent',b, ...
	'Color',[0 0 1], ...
	'EraseMode','xor', ...
	'Tag','mappingcurve', ...
	'XData',mat2, ...
	'YData',mat3);
	set(b,'UserData',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.497222 1.01254 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.497222 -0.0532915 0], ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0638889 0.495298 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.225 1.08777 0], ...
	'Tag','Axes1Text1', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','bendline closebtn', ...
	'Position',[506 13 108 20], ...
	'String','closebtn', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.733333 0.733333 0.733333], ...
	'Position',[507 356 103 20], ...
	'String',['linear '], ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','bendline resetbtn', ...
	'Position',[508 313 100 20], ...
	'String','reset', ...
	'Tag','resetbtn');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.733333 0.733333 0.733333], ...
	'Position',[587 236 29 20], ...
	'String','Hz', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.733333 0.733333 0.733333], ...
	'Position',[632 238 60 20], ...
	'String','Hz', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.733333 0.733333 0.733333], ...
	'Position',[588 198 26 20], ...
	'String','Hz', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[508 240 82 20], ...
	'Style','edit', ...
	'Tag','ofqedit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[508 202 82 20], ...
	'Style','edit', ...
	'Tag','newfqedit');
